version: "3.9"

services:
  fast_openai:
    build: .
    container_name: fast_openai
    ports:
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - open-network
    restart: always

networks:
  open-network:
    external: true
